import 'package:i_trade/views/components/screens/menu_item_model.dart';

//LISTE DES PRODUITS DEMO_DATA DU PROJET
// ON AJOUTE OU SUPPRIME DES OBJETS DANS CETTE LISTE POUR MODIFIER LA LISTE DES PRODUITS
final List<MenuItemModel> demoData = [
  MenuItemModel(
    name: 'Kenzio shop',
    description: 'Playstation 5 ...',
    detailsproduits: 'Playstation 5 (PS4) Pro + 1 manette. \nVersion 12.00 ...',
    price: '350 000 FCFA',
    image: 'assets/images/playstation5.png',
    categorie: 'Console',
  ),
  MenuItemModel(
    name: 'Kenzia shop',
    description: 'Casque steel ...',
    detailsproduits: 'Iphone 13 pro ...',
    price: '420 000 FCFA',
    image: 'assets/images/casquesteel.png',
    categorie: 'Casque',
  ),
  MenuItemModel(
    name: 'Guy store',
    description: 'Iphone 13 pro ...',
    detailsproduits: 'Iphone 13 pro ...',
    price: '210 000 FCFA',
    image: 'assets/images/samsung1.png',
    categorie: 'Android',
  ),
  MenuItemModel(
    name: 'NAG shop',
    description: 'Xiaomi 12 pro ...',
    detailsproduits: 'Iphone 13 pro ...',
    price: '250 000 FCFA',
    image: 'assets/images/xiaomi-12pro.png',
    categorie: 'Android',
  ),
  MenuItemModel(
    name: 'NAG shop',
    description: 'Xiaomi 14 ...',
    detailsproduits: 'Iphone 13 pro ...',
    price: '420 000 FCFA',
    image: 'assets/images/xiaomi-14.png',
    categorie: 'Android',
  ),
  MenuItemModel(
    name: 'Guy store',
    description: 'Iphone 15 pro ...',
    detailsproduits: 'Iphone 13 pro ...',
    price: '500 000 FCFA',
    image: 'assets/images/iphone15rpomax.png',
    categorie: 'Iphone',
  ),
  MenuItemModel(
    name: 'Guy store',
    description: 'Tablette PZ3 ...',
    detailsproduits: 'Tablette new Generation ...',
    price: '89 000 FCFA',
    image: 'assets/images/tablette.png',
    categorie: 'Autre',
  ),
  MenuItemModel(
    name: 'Kenzo shop',
    description: 'Montre P9 ...',
    detailsproduits: 'Montre connecté étanche ...',
    price: '90 000 FCFA',
    image: 'assets/images/montre_connecter.png',
    categorie: 'Montre',
  ),
  MenuItemModel(
    name: 'NAG shop',
    description: 'Setup Gameur...',
    detailsproduits: 'I9 12 Genetation 32G de ram 1T ssd. \n montage sur place',
    price: '800 000 FCFA',
    image: 'assets/images/setupgameur.png',
    categorie: 'Pc',
  ),
  MenuItemModel(
    name: 'Guy store',
    description: 'Ordinateur Hp...',
    detailsproduits: 'Playstation 5 (PS4) Pro + 1 manette. \n Version 12.00',
    price: '200 000 FCFA',
    image: 'assets/images/ordinateurportable.png',
    categorie: 'Pc',
  ),
  MenuItemModel(
    name: 'Guy store',
    description: 'Iphone XR...',
    detailsproduits: 'Playstation 5 (PS4) Pro + 1 manette. \nVersion 12.00',
    price: '210 000 FCFA',
    image: 'assets/images/iphonexr.png',
    categorie: 'Iphone',
  ),
  MenuItemModel(
    name: 'Kenzo shop',
    description: 'Google pixel 9 ...',
    detailsproduits: 'Iphone 13 pro ...',
    price: '300 000 FCFA',
    image: 'assets/images/Google pixel 9.png',
    categorie: 'Android',
  ),
  MenuItemModel(
    name: 'Guy store',
    description: 'Casque...',
    detailsproduits: 'Playstation 5 (PS4) Pro + 1 manette. \nVersion 12.00',
    price: '210 000 FCFA',
    image: 'assets/images/casquehyperx.png',
    categorie: 'Casque',
  ),
  MenuItemModel(
    name: 'NAG shop',
    description: 'Iphone 256G...',
    detailsproduits: 'Playstation 5 (PS4) Pro + 1 manette.\n Version 12.00',
    price: '250 000 FCFA',
    image: 'assets/images/iphone3.png',
    categorie: 'Iphone',
  ),
];
